### ISSUE TITLE
Source if model?

### ISSUE THREAD

**Issue by KevinBurton** [dsuryd/dotNetify#1]
I was going through the examples and I notice:

      public ActionResult Demo(string id, object iModel)
      {
         if (String.IsNullOrEmpty(id))
            id = "index";

         if (id.EndsWith("_cshtml"))
            return View("/Views/" + id.Replace("_cshtml", ".cshtml"), iModel != null && iModel.GetType() != typeof(object) ? iModel : null);
         return File(Server.MapPath("/Views/" + (id.EndsWith(".html") ? id : id + ".html")), "text/html");
      }

But I am not sure where the object iModel is generated?

Ideas?

**Comment by dsuryd** [comment]
Hi, the iModel here is used only by the last example that demonstrates server-side routing with Razor.   For all the other examples, it will always be null, and can be safely ignored - this Action will just return plain HTML file.

**Comment by KevinBurton** [comment]
Just for my info what populates it with a non-null value? I notice that clicking on any of the samples results in a non-null value.

**Comment by dsuryd** [comment]
Sorry, my info's a bit incorrect - a non-null value seems to be passed when this action is called by the ASP.NET Controller although it has no significance for the app and should be ignored.  The actual use of this parameter is on the Web Store example when the action Routing() calls it:

      public ActionResult Routing(RoutingViewData iViewData)
      {
         IRoutable model;
         var viewId = RoutableExtension.Route(ref iViewData, out model);
         if (viewId != null)
         {
            ViewData["Routing"] = iViewData;
            return Demo(viewId.Replace("/Demo/", ""), model);
         }
         return new EmptyResult();
      }

The name "model" refers to the ASP.NET MVC model object to be passed to the Razor through Controller.View() method; but what's actually being passed is the view model object that the dotNetify router library instantiates so that the Razor can do server-side rendering of the HTML view with data from that view model.
