### ISSUE TITLE
Getting the equivalent to connectionid in SignalR

### ISSUE THREAD

**Issue by KristofferStrube** [dsuryd/dotNetify#108]
I know that you can get the context (and through that the connectionid) through MiddelWare, but I would like to access the connectionid in the same way that you can in SignalR directly from the hub.

Is this possible in the DotNetifyHub or can it only be accessed in an implementation of Middleware?

**Comment by dsuryd** [comment]
Do I understand you correctly that you would like to access the SignalR connection ID from your view model instance ?

It can only be done indirectly through VMFilter because in principle view model abstractions should not be aware of lower-layer infrastructure details, and if the use case requires that coupling, it should be made explicit.

The implementation with VMFilter is pretty easy:

1. Add the attribute and filter classes:
```csharp
public class SetConnectionIdAttribute : Attribute { }

public class SetConnectionIdFilter : IVMFilter<SetConnectionIdAttribute>
{
    public Task Invoke(SetConnectionIdAttribute attr, VMContext vmContext, NextFilterDelegate next)
    {
        var propInfo = vmContext.Instance.GetType().GetTypeInfo().GetProperty("ConnectionId");
        propInfo?.SetValue(vmContext.Instance, vmContext.HubContext.CallerContext.ConnectionId);
        return next(vmContext);
    }
}
```

2. Include the filter in the config:
```csharp
app.UseDotNetify(config => config.UseFilter<SetConnectionIdFilter>());
```

3. Add the attribute and the ConnectionId prop to the view model:
```csharp
 [SetConnectionId]
public class MyViewModel: BaseVM
{
   public string ConnectionId { get; set; }
}
```

ConnectionId will be set after the constructor call.   

If this is still not sufficient for your use case, we can discuss further.

**Comment by KristofferStrube** [comment]
It was exactly what I needed

Thanks for the quick response
 - Kristoffer Strube

tor. 26. jul. 2018 18.55 skrev Dicky Suryadi <notifications@github.com>:
