### ISSUE TITLE
Problem with resource usage

### ISSUE THREAD

**Issue by mojo-man** [dsuryd/dotNetify#143]
When I first start my REACT application (with the dotnetify code using MulticastVM) my c# process is running at approx. 12% CPU. When I refresh the REACT page, the c# process jumps to 100% CPU. When I refresh it again, it jumps to 200% CPU. I am overriding Dispose in my VM implementation. Wondering if there is something else that I should be overriding to handle when a SignalR connection is closed.

**Comment by dsuryd** [comment]
Check if your Dispose gets called on refresh.  See issue #71.

**Comment by mojo-man** [comment]
I confirmed that my Dispose is being called as expected. I will try moving the `vm$destroy()` as discussed in the referenced article.

**Comment by mojo-man** [comment]
I moved `vm$destroy()` to a window beforeunload handler/listener as described in the referenced issue - and there is no change.

**Comment by mojo-man** [comment]
Any ideas?

**Comment by dsuryd** [comment]
There is no indication that MulticastVM or anything in the dotNetify library would consume CPU resources in the manner described.  It's not reproducible on my end.   If you still feel this is caused by a bug in this library, then in order to move forward, I will need either steps to reproduce, or a simple, self-contained app that I can run and observe the issue.

**Comment by mojo-man** [comment]
I am working on a react-based test fixture that I can use to isolate the issue. I'll re-open if I find anything.
