### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by dlarosa** [dsuryd/dotNetify#2]
Love this project, thanks for open sourcing it. How can I contribute? Is there a roadmap somewhere? Are you planning on keeping a list features/bugs somewhere?

**Comment by dsuryd** [comment]
Hi, thank's for asking!  At this stage, there are two main things I'd love people to participate: 1) start using the code-base and submit bugs / issues so that by Q1 2016 we could do a stable v1 release, and 2) to get the word out on this project and get more people involved.  This Github Issues will be a great place to submit/track bugs and feature requests.

My vision for this project is to provide a strong alternative to doing web app development, with the emphasis on simplicity, ease-of-use, and powerful tooling that allows the development to be done rapidly and be highly maintainable in the long run.   Although I have a few ideas to what things could be done next, e.g. web components with bindable properties,  I am yet to formulate specific roadmap, and I think I'd rather it's done within a community of people who care about the project.

**Comment by dlarosa** [comment]
Sounds like a plan, I will log any bug I find or idea I come up with on Github Issues. Hopefully, we can get enough people interested in collaborating on this project soon.
