### ISSUE TITLE
Authentication with dotNetify

### ISSUE THREAD

**Issue by JasonWeise** [dsuryd/dotNetify#25]
Hi
I am evaluating dotNetify for a new project and think the solution is excellent.
Before we adopt this solution I just have one question regarding authentication, we require a capability to restrict a part of our dashboard to logged in users but cannot see an example of how you achieve that with dotNetify.

Do you have an example project with authentication or a tutorial tucked away somewhere?

Thanks in advance.

**Comment by dsuryd** [comment]
There's a demo web app that uses Google authentication.  It uses Knockout front-end, but otherwise the same C# back-end:   [https://github.com/dsuryd/dotNetify-app-template](https://github.com/dsuryd/dotNetify-app-template).  I assume you've read the [ topic on security](http://www.dotnetify.net/react/Security) on the website.
