### ISSUE TITLE
Return Http status codes and authentication, authorization

### ISSUE THREAD

**Issue by parissge** [dsuryd/dotNetify#29]
I am very interested for this framework and kudos to the creator.
Currently i am starting a new project and although i want to use dotNetify there are a lot of things keeping me back, things that i don't understand currently and there is not a proper documentation that covers every scenario.

What i would like to ask in this post is how we return http status codes? And how do we apply authentication and authorization on view models?

Also how we can take advantage of the DI in asp.net core, what is the role of the Http request pipeline now that almost all requests are through SignalR, can i use ActionFilters, or serve static content, how to add log and audit capabilities? Previously i could register a middleware and i was done, now with SignalR the picture is not clear for me.

Plus, is there somewhere a roadmap with what is currently under development, what are the next steps for the framework?

Again well done to the creator(s) of this framework, i really like it but i need to be more confident before i dive in.

**Comment by dsuryd** [comment]
Thank you for your interest!  Your questions are exactly the feedback I've been expecting.  It will require a good deal of thoughts for me to respond, but I'll get back to you as soon as I can.

**Comment by parissge** [comment]
Thank you for your response.

Of course what I asked is a small set of questions that keep coming in my mind but if I want to summarize them somehow I would ask this. **Is it possible to execute the middleware that is already setup in ASP.NET Core for each incoming and outgoing SignalR requests and responses without actually having an Http Request from the client?** The benefits by doing this will be enormous.

Thank you again.

**Comment by dsuryd** [comment]
> Currently i am starting a new project and although i want to use dotNetify there are a lot of things keeping me back, things that i don't understand currently and there is not a proper documentation that covers every scenario.

Questions on this forum such as yours will help me improve this library and its documentation, so thank you for asking!

> What i would like to ask in this post is how we return http status codes?  And how do we apply authentication and authorization on view models?

Client fetching the HTML page resources from the server should go through the normal ASP.NET authentication process, with the controller or the HTTP middleware returning the status code.  Once the HTML page script is executed on the client, dotNetify establishes the SignalR connection within the same authentication context.  It is a persistent connection, so once authenticated, subsequent communication  won't carry auth tokens the way web API calls do.  SignalR server hub has access to the auth claims, which dotNetify then makes available to the view models.  

For additional security, an [Authorize] class attribute (DotNetify.Security namespace) can be added to a view model to get the dotNetify middleware check whether user is still authenticated before invoking the view model.  This API is not documented yet as it is still under evaluation. 

A view model can specify IPrincipalAccessor in its constructor to get access to the claims auth context.  This object is made available by default through ASP.NET Core DI.  The view model can use this to control which view elements a client may have access to.

> Also how we can take advantage of the DI in asp.net core, 

View model instantiation by default uses ASP.NET Core DI, therefore all registered services can be injected to any view model.

I have a sample app that demonstrates authentication and DI capability:  [dotNetify-app-template](https://github.com/dsuryd/dotNetify-app-template)

Granted, this authentication/authorization facility is incipient and requires a lot of feedback, and so if you're looking for a no-risk, mature library for your next project, I'd have to caution you.

> what is the role of the Http request pipeline now that almost all requests are through SignalR, can i use ActionFilters, or serve static content, how to add log and audit capabilities? Previously i could register a middleware and i was done, now with SignalR the picture is not clear for me.

> Is it possible to execute the middleware that is already setup in ASP.NET Core for each incoming and outgoing SignalR requests and responses without actually having an Http Request from the client? The benefits by doing this will be enormous.

HTTP pipelines/filters won't work on SignalR communication.  SignalR has its own pipeline in ASP.NET, but as far as I know, it's been taken away in ASP.NET Core last year's alpha version.  The first RC version of SignalR for .NET Core v2.0 is at least still months away and no documentation yet on the APIs.  With that said, I think the capability to allow writing some form of middlewares to inspect SignalR messages before they're passed to the view models is a definite possibility; something that I will look into.

> Plus, is there somewhere a roadmap with what is currently under development, what are the next steps for the framework?  Again well done to the creator(s) of this framework, i really like it but i need to be more confident before i dive in.

I have stated before that my long-term goal for this project is to get to a state where it can support full-stack micro-service on .NET platform: the ability to have a complex web app composable of independent front+back-end modules that can be worked on and deployed by completely autonomous teams with minimal downtime.

There isn't a definite roadmap yet other than migration to SignalR .NET Core v2.0 once it's out.  My current focus is on garnering interests through blogging interesting applications of this library and paying attentions to what interested people such as yourself are saying, in order to shape that roadmap.

**Comment by dsuryd** [comment]
Nuget v2.2.0-pre now includes capability to create middlewares and view model filters, support for JWT authentication and view model authorization.
