### ISSUE TITLE
Unable to use websockets

### ISSUE THREAD

**Issue by acronoah** [dsuryd/dotNetify#42]
If I follow the instructions in the [help](http://dotnetify.net/react/Installation) I end up getting the following exception if I try to use websockets from the client.  Long-polling works...

System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.AspNetCore.SignalR.Server.Resources.resources" was correctly embedded or linked into assembly "Gray.Microsoft.AspNetCore.SignalR.Server" at compile time, or that all the satellite assemblies required are loadable and fully signed.

**Comment by dsuryd** [comment]
What OS were you on?  Websocket requires minimum Win 8 or Win Server 2012.  Try the [HelloWorld example from here](https://github.com/dsuryd/dotnetify-react-demo-vs2017); I just re-tested on Win 10, websocket is working.

**Comment by acronoah** [comment]
Mac OS, .NET core 2.0.

There's no websocket support outside of windows??

Thanks for the quick reply, btw.

**Comment by dsuryd** [comment]
What I said is only true for Windows.  .NET Core websockets server can run on Mac OS, I just tested with .NET Core v1.1 on El Capitan running with Chrome.  I can see websocket communication on the developer tool.  I couldn't use v2.0 because it requires Sierra, but perhaps if you see an error, there's compatibility issue with the package I'm using with Mac on v2.0.  Note that SignalR for .NET Core v2.0 is still in development; what dotNetify is using for .NET Core is an unofficial fork of the alpha v1.x.  DotNetify will officially support .NET Core 2.0 once SignalR for v2.0 is released.

**Comment by noah79** [comment]
Thanks for the write-up.  Hopefully signalR will show up soon...
