### ISSUE TITLE
Session State

### ISSUE THREAD

**Issue by poppie** [dsuryd/dotNetify#7]
I would like to pass into the MasterVM some values from session state.  How would I get access to the HttpContext?

**Comment by dsuryd** [comment]
While you can access the `HttpContext` instance from `System.Web.HttpContext.Current`, SignalR by design does not support the session state and will set the `Session` variable to null.  You will have to find some other way to store the values, e.g. what's suggested [here](http://stackoverflow.com/questions/11833336/work-around-for-session-for-signalr).

**Comment by poppie** [comment]
dotNetify is awesome. How can I pass into data-vm-arg not only simple properties but also serialized complex objects?

**Comment by dsuryd** [comment]
You can pass JSON string of the object, for example:

```
public class TestVM: BaseVM
{ 
   public class B { public string PropB { get; set; } }
   public class A { public B PropA { get; set; } }

   public A ParamA { get; set; }
}
```

` <div data-vm="TestVM" data-vm-arg="{'ParamA': {'PropA': {'PropB': 'test'}}}">`

But, can you share the specific use case of why you need to pass complex objects on the HTML?
