### ISSUE TITLE
IdentityServer4 Integration

### ISSUE THREAD

**Issue by jsaez868** [dsuryd/dotNetify#73]
Hi @dsuryd ,

First off, I'd like to say it's a very nice framework - it's simple yet powerful. 

We've been playing with the framework and as far as beefing up security, do you have any sample that integrates with IdentityServer4?

Thanks in advance!

**Comment by dsuryd** [comment]
I don't have anything specific to IdentityServer4, only [ASOS](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server).  It was used as an independent [auth server](https://github.com/dsuryd/dotnetify-react-demo-vs2017/blob/master/ReactTemplate/content/server/AuthServer.cs) to generate tokens for client-side dotNetify to include in the request header, then extracted by server-side dotNetify's middleware into ClaimsPrincipal for the context.   Since they're both based on OpenIdConnect/OAuth2, it's probably not difficult to port.
