### ISSUE TITLE
MapDotNetifyHub() throws Exception in .NET Core 2.1

### ISSUE THREAD

**Issue by AndrejLitke** [dsuryd/dotNetify#80]
Hi dsuryd,

I tried to use .Net Core 2.1 in my web application.
But since than the methode MepDotNetifyHub() throws the Exception 
"The path in 'value' must start with '/'."

Can you give me a hint what I can do to solve this.

Thanks in advance for your help and general for the great framework

Andrej

**Comment by dsuryd** [comment]
Hi, you are seeing that issue because .net core 2.1 uses the latest signalR (preview1), but current published version of dotNetify is still one version behind (alpha2).   I'm planning to publish the next version of dotNetify when [signalR preview2](https://github.com/aspnet/SignalR/milestone/9) is out.

**Comment by AndrejLitke** [comment]
Thank you for your fast reply. 
I will wait, then with the upgrade to .net 2.1.

**Comment by dsuryd** [comment]
DotNetify has been upgraded to signalR v1.0.0-preview2, should now be compatible w/ .netcore2.1.
